add_requires("sqlite3")

target("ObjDBSQLite", function ()
    set_default(false)
    set_kind("static")
    add_deps("ObjDB", { public = true })
    add_packages("sqlite3", { public = true })
    add_includedirs("src", { public = true })
    add_files("src/*.m")
end)
