target("AsyncRT.Common", function ()
    set_kind("static")
    add_includedirs("../..", { public = true })
    add_headerfiles("*.h", { prefixdir = "AsyncRT/Common" })
    set_pcheader("Common.h")
    add_files("*.m")
end)
