target("AsyncRTWebUI", function ()
    set_kind(get_config("kind") == "shared" and "shared" or "static")

    add_deps("AsyncRTApplicationUIBase", "AsyncRTNetworkingHTTP", { public = true })
    add_includedirs("../../../..", { public = true })
    add_headerfiles("(Application.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web" })
    add_headerfiles("(Component.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web" })
    add_headerfiles("(DOM.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web" })
    add_headerfiles("(Request.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web" })
    add_headerfiles("(View.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web" })
    add_headerfiles("(Web.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web" })
    add_headerfiles("Platform/HTTPServer/(View.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web/Platform/HTTPServer" })
    add_headerfiles("Platform/WKWebKit/(View.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web/Platform/WKWebKit" })
    add_headerfiles("Platform/WebKitGTK/(View.h)", { prefixdir = "AsyncRT/Application/UI/Surface/Web/Platform/WebKitGTK" })
    add_extrafiles("Component.js", "Platform/HTTPServer/Bridge.js")
    add_files("*.m", "Platform/HTTPServer/View.m")
end)
